name: strip
version: 0.0.0
license: MIT
copyright: (c) 2013 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
 - base == 4.*

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: strip
